name: build
on: push
jobs:
    build:
        name: make_stubs
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@master
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                python-version: 3.8
            - name: Build Stubs
              id: build
              run: python build_zastub.py
